name: "⚠ 错误报告"
description: "启动器出现闪退、卡死、不正常运行或弹出了报错窗口"
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我确认这个问题可以被复现，且不是人为触发的"
      required: true
    - label: "我明白启动器的维护者可能没有时间处理此Issue"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 报告内容
    description: "粘贴单击复制按钮复制的完整异常信息"
    placeholder: |
      FSL.Next 错误报告信息
      -Environment Launcher X.X, OS Microsoft Windows NT 10.X, XXXX/XX/XX XX:XX:XX
      ······
  validations:
    required: true
